{% set version = "1.9.0" %}

package:
  name: tensorflow-{{ variant }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [not x86_64]

requirements:
  run:
    - tensorflow =={{ version }}
    - _tflow_190_select =={{ select_version }}

test:
  imports:
    - tensorflow
    - tensorboard
  commands:
    # has an exit code of 1, see tensorboard recipe
    - tensorboard --help | grep USAGE  # [unix]

about:
  summary: Metapackage for selecting a TensorFlow variant.
